/** Client-side mirrors of the backend DTOs (no Prisma import). */

export type ProjectStatus =
  | "NEW"
  | "WAITING_MATERIAL"
  | "EDITING"
  | "REVIEW"
  | "ADJUSTMENTS"
  | "DELIVERED"
  | "CANCELLED";

export type Priority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";
export type PaymentStatus = "PENDING" | "PARTIAL" | "PAID";
export type FinancialType = "INCOME" | "EXPENSE";
export type FinancialStatus = "PENDING" | "PARTIAL" | "PAID" | "CANCELLED";

export interface ApiEnvelopeMeta {
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
  [k: string]: unknown;
}

export interface Client {
  id: string;
  name: string;
  companyName: string | null;
  email: string | null;
  phone: string | null;
  whatsapp: string | null;
  instagram: string | null;
  notes: string | null;
  projectsCount?: number;
  createdAt: string;
  updatedAt: string;
}

export interface KanbanColumn {
  id: string;
  name: string;
  slug: string;
  position: number;
  color: string | null;
  isDeliveredColumn: boolean;
  isDefault: boolean;
  cardsCount?: number;
  createdAt: string;
  updatedAt: string;
}

export interface ProjectKanbanInfo {
  columnId: string;
  columnName: string;
  columnSlug: string;
  position: number;
}

export interface Payment {
  id: string;
  financialRecordId: string;
  amount: number;
  paymentDate: string;
  paymentMethod: string | null;
  notes: string | null;
  createdAt: string;
}

export interface FinancialRecord {
  id: string;
  projectId: string | null;
  clientId: string | null;
  type: FinancialType;
  category: string;
  description: string;
  amount: number;
  paidAmount: number;
  remainingAmount: number;
  status: FinancialStatus;
  dueDate: string | null;
  paidAt: string | null;
  referenceMonth: number;
  referenceYear: number;
  paymentMethod: string | null;
  notes: string | null;
  autoGenerated: boolean;
  payments?: Payment[];
  project?: { id: string; title: string } | null;
  client?: { id: string; name: string } | null;
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: string;
  clientId: string;
  client?: { id: string; name: string; companyName: string | null };
  title: string;
  description: string | null;
  projectType: string | null;
  value: number;
  entryDate: string;
  deadline: string | null;
  deliveredAt: string | null;
  completedAt: string | null;
  status: ProjectStatus;
  priority: Priority;
  paymentStatus: PaymentStatus;
  paymentMethod: string | null;
  color: string | null;
  notes: string | null;
  kanban: ProjectKanbanInfo | null;
  financial?: FinancialRecord[];
  createdAt: string;
  updatedAt: string;
}

export interface Activity {
  id: string;
  projectId: string | null;
  action: string;
  description: string;
  metadata: unknown;
  createdAt: string;
}

export interface DashboardSummary {
  period: { month: number; year: number };
  revenue: { forecast: number; received: number; pending: number };
  expenses: { total: number; paid: number; pending: number };
  netProfit: number;
  projectedNetProfit: number;
  projects: { total: number; delivered: number; inProgress: number; cancelled: number };
  averageTicket: number;
}

export interface ChartDelta {
  current: number;
  previous: number;
  change: number;
  changePct: number | null;
}

export interface DashboardCharts {
  range: { from: { month: number; year: number }; to: { month: number; year: number }; months: number };
  monthlyRevenue: { key: string; label: string; forecast: number; received: number; pending: number }[];
  incomeVsExpense: { key: string; label: string; income: number; expense: number; net: number }[];
  projectsByStatus: { status: ProjectStatus; count: number; value: number }[];
  financialEvolution: {
    key: string;
    label: string;
    cumulativeForecast: number;
    cumulativeReceived: number;
    monthlyNet: number;
  }[];
  monthComparison: {
    current: { key: string; label: string };
    previous: { key: string; label: string } | null;
    revenue: ChartDelta;
    received: ChartDelta;
    expenses: ChartDelta;
    net: ChartDelta;
  } | null;
}

export interface MonthlyReport {
  period: { month: number; year: number; label: string };
  rows: {
    projectId: string;
    projectTitle: string;
    clientId: string;
    clientName: string;
    value: number;
    received: number;
    pending: number;
    paymentStatus: PaymentStatus;
    deliveredAt: string | null;
  }[];
  summary: {
    grossRevenue: number;
    totalReceived: number;
    totalPending: number;
    averageTicket: number;
    jobsCount: number;
  };
}

export interface KanbanBoardColumn {
  id: string;
  name: string;
  slug: string;
  color: string | null;
  position: number;
  isDeliveredColumn: boolean;
  isDefault: boolean;
  cards: {
    projectId: string;
    position: number;
    title: string;
    value: number;
    status: ProjectStatus;
    priority: Priority;
    paymentStatus: PaymentStatus;
    color: string | null;
    deadline: string | null;
    client: { id: string; name: string; companyName: string | null } | null;
  }[];
}
