import type {
  Activity,
  Client,
  FinancialRecord,
  KanbanColumn,
  Payment,
  Project,
  ProjectKanban,
} from "@prisma/client";
import { toNumber } from "@/utils/money";
import type {
  ActivityDTO,
  ClientDTO,
  FinancialRecordDTO,
  KanbanColumnDTO,
  PaymentDTO,
  ProjectDTO,
} from "@/types";

type ClientRow = Client & { _count?: { projects: number } };

export function serializeClient(row: ClientRow): ClientDTO {
  return {
    id: row.id,
    name: row.name,
    companyName: row.companyName,
    email: row.email,
    phone: row.phone,
    whatsapp: row.whatsapp,
    instagram: row.instagram,
    notes: row.notes,
    projectsCount: row._count?.projects,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

type ColumnRow = KanbanColumn & { _count?: { cards: number } };

export function serializeColumn(row: ColumnRow): KanbanColumnDTO {
  return {
    id: row.id,
    name: row.name,
    slug: row.slug,
    position: row.position,
    color: row.color,
    isDeliveredColumn: row.isDeliveredColumn,
    isDefault: row.isDefault,
    cardsCount: row._count?.cards,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

export function serializePayment(row: Payment): PaymentDTO {
  return {
    id: row.id,
    financialRecordId: row.financialRecordId,
    amount: toNumber(row.amount),
    paymentDate: row.paymentDate,
    paymentMethod: row.paymentMethod,
    notes: row.notes,
    createdAt: row.createdAt,
  };
}

type FinancialRow = FinancialRecord & {
  payments?: Payment[];
  project?: { id: string; title: string } | null;
  client?: { id: string; name: string } | null;
};

export function serializeFinancial(row: FinancialRow): FinancialRecordDTO {
  const amount = toNumber(row.amount);
  const paidAmount = toNumber(row.paidAmount);
  return {
    id: row.id,
    projectId: row.projectId,
    clientId: row.clientId,
    type: row.type,
    category: row.category,
    description: row.description,
    amount,
    paidAmount,
    remainingAmount: Math.max(0, Number((amount - paidAmount).toFixed(2))),
    status: row.status,
    dueDate: row.dueDate,
    paidAt: row.paidAt,
    referenceMonth: row.referenceMonth,
    referenceYear: row.referenceYear,
    paymentMethod: row.paymentMethod,
    notes: row.notes,
    autoGenerated: row.autoGenerated,
    payments: row.payments?.map(serializePayment),
    project: row.project ?? undefined,
    client: row.client ?? undefined,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

type ProjectRow = Project & {
  client?: { id: string; name: string; companyName: string | null };
  kanban?:
    | (ProjectKanban & { column?: { id: string; name: string; slug: string } })
    | null;
  financialRecords?: FinancialRow[];
};

export function serializeProject(row: ProjectRow): ProjectDTO {
  return {
    id: row.id,
    clientId: row.clientId,
    client: row.client,
    title: row.title,
    description: row.description,
    projectType: row.projectType,
    value: toNumber(row.value),
    entryDate: row.entryDate,
    deadline: row.deadline,
    deliveredAt: row.deliveredAt,
    completedAt: row.completedAt,
    status: row.status,
    priority: row.priority,
    paymentStatus: row.paymentStatus,
    paymentMethod: row.paymentMethod,
    color: row.color,
    notes: row.notes,
    kanban: row.kanban
      ? {
          columnId: row.kanban.columnId,
          columnName: row.kanban.column?.name ?? "",
          columnSlug: row.kanban.column?.slug ?? "",
          position: row.kanban.position,
        }
      : null,
    financial: row.financialRecords?.map(serializeFinancial),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

export function serializeActivity(row: Activity): ActivityDTO {
  return {
    id: row.id,
    projectId: row.projectId,
    action: row.action,
    description: row.description,
    metadata: row.metadata,
    createdAt: row.createdAt,
  };
}
