import { Prisma, ProjectStatus, type Project } from "@prisma/client";
import { logActivity } from "@/services/activity.service";
import {
  deriveFinancialStatus,
  inferIncomeCategory,
  paymentToFinancialStatus,
} from "@/services/financial.rules";
import { nowRef } from "@/utils/date";

type Tx = Prisma.TransactionClient;

/**
 * ─────────────────────────────────────────────────────────────
 * Kanban ↔ Financial automation
 *
 *   CLIENT → PROJECT → KANBAN → "DELIVERED" column
 *          → auto FinancialRecord (INCOME) → dashboard updates
 *
 * Guarantees:
 *   • exactly one auto-generated INCOME record per project
 *     (enforced by FinancialRecord.autoSourceProjectId @unique)
 *   • "delivered" and "paid" stay independent
 *   • project value changes propagate to the auto record
 *   • cancelling a project can keep or void its auto record
 * ─────────────────────────────────────────────────────────────
 */

const DELIVERED_STATUSES: ProjectStatus[] = [ProjectStatus.DELIVERED];

export interface DeliverResult {
  financialRecordId: string | null;
  created: boolean;
}

/**
 * Called when a project enters a "delivered" state (moved to the delivered
 * column, or status set to DELIVERED directly). Idempotent.
 */
export async function onProjectDelivered(
  tx: Tx,
  project: Project,
  opts: { deliveredAt?: Date; reason: "kanban" | "status" } = { reason: "status" },
): Promise<DeliverResult> {
  const deliveredAt = opts.deliveredAt ?? project.deliveredAt ?? new Date();

  // 1. Normalize the project state.
  await tx.project.update({
    where: { id: project.id },
    data: {
      status: ProjectStatus.DELIVERED,
      deliveredAt,
      completedAt: project.completedAt ?? deliveredAt,
    },
  });

  // 2. Nothing to bill for a zero-value project — skip (a later value change
  //    will call onProjectValueChanged which creates the record).
  const value = new Prisma.Decimal(project.value);
  const existing = await tx.financialRecord.findUnique({
    where: { autoSourceProjectId: project.id },
  });

  if (value.lte(0)) {
    return { financialRecordId: existing?.id ?? null, created: false };
  }

  const ref = nowRef(deliveredAt);
  const category = inferIncomeCategory(project.projectType);

  if (existing) {
    // 3a. Keep payments, refresh the billable facts, recompute status.
    const status = deriveFinancialStatus(value, existing.paidAmount, existing.status);
    const updated = await tx.financialRecord.update({
      where: { id: existing.id },
      data: {
        amount: value,
        description: project.title,
        clientId: project.clientId,
        projectId: project.id,
        referenceMonth: ref.month,
        referenceYear: ref.year,
        status,
        paidAt: status === "PAID" ? existing.paidAt ?? deliveredAt : existing.paidAt,
      },
    });
    return { financialRecordId: updated.id, created: false };
  }

  // 3b. First delivery → create the auto record.
  const seedStatus = paymentToFinancialStatus(project.paymentStatus);
  const paidAmount =
    seedStatus === "PAID" ? value : new Prisma.Decimal(0);

  const record = await tx.financialRecord.create({
    data: {
      userId: project.userId,
      projectId: project.id,
      clientId: project.clientId,
      type: "INCOME",
      category,
      description: project.title,
      amount: value,
      paidAmount,
      status: seedStatus,
      paidAt: seedStatus === "PAID" ? deliveredAt : null,
      referenceMonth: ref.month,
      referenceYear: ref.year,
      paymentMethod: project.paymentMethod,
      autoGenerated: true,
      autoSourceProjectId: project.id,
    },
  });

  await logActivity(
    {
      userId: project.userId,
      projectId: project.id,
      action: "FINANCIAL_CREATED",
      description: `Lançamento automático criado para "${project.title}" (${ref.month}/${ref.year})`,
      metadata: {
        financialRecordId: record.id,
        amount: value.toString(),
        trigger: opts.reason,
      },
    },
    tx,
  );

  return { financialRecordId: record.id, created: true };
}

/**
 * Called when a delivered project is moved back to a non-delivered column or
 * its status changes away from DELIVERED.
 */
export async function onProjectReopened(
  tx: Tx,
  project: Project,
  newStatus: ProjectStatus,
): Promise<void> {
  await tx.project.update({
    where: { id: project.id },
    data: {
      status: newStatus,
      deliveredAt: null,
      completedAt: null,
    },
  });

  const auto = await tx.financialRecord.findUnique({
    where: { autoSourceProjectId: project.id },
    include: { _count: { select: { payments: true } } },
  });

  if (auto && auto._count.payments === 0 && auto.status !== "CANCELLED") {
    // No money moved yet → safe to remove the premature record.
    await tx.financialRecord.delete({ where: { id: auto.id } });
    await logActivity(
      {
        userId: project.userId,
        projectId: project.id,
        action: "FINANCIAL_DELETED",
        description: `Lançamento automático removido — projeto "${project.title}" reaberto`,
        metadata: { financialRecordId: auto.id },
      },
      tx,
    );
  }
}

/**
 * Propagate a project value change to its auto-generated financial record.
 * Creates the record if the project is already delivered and none exists yet.
 */
export async function onProjectValueChanged(
  tx: Tx,
  project: Project,
): Promise<void> {
  const auto = await tx.financialRecord.findUnique({
    where: { autoSourceProjectId: project.id },
  });
  const value = new Prisma.Decimal(project.value);

  if (!auto) {
    if (project.status === ProjectStatus.DELIVERED && value.gt(0)) {
      await onProjectDelivered(tx, project, {
        deliveredAt: project.deliveredAt ?? undefined,
        reason: "status",
      });
    }
    return;
  }

  if (value.lte(0)) {
    // Value zeroed out — void the auto record when nothing has been paid.
    const payments = await tx.payment.count({ where: { financialRecordId: auto.id } });
    if (payments === 0) {
      await tx.financialRecord.update({
        where: { id: auto.id },
        data: { status: "CANCELLED" },
      });
    }
    return;
  }

  const status = deriveFinancialStatus(value, auto.paidAmount, auto.status);
  await tx.financialRecord.update({
    where: { id: auto.id },
    data: { amount: value, status },
  });

  await logActivity(
    {
      userId: project.userId,
      projectId: project.id,
      action: "FINANCIAL_UPDATED",
      description: `Valor do lançamento automático atualizado para ${value.toString()}`,
      metadata: { financialRecordId: auto.id },
    },
    tx,
  );
}

/**
 * Called when a project is cancelled. `policy`:
 *   • "keep"   → leave the financial history untouched
 *   • "cancel" → set the auto record (and manual pending records) to CANCELLED
 */
export async function onProjectCancelled(
  tx: Tx,
  project: Project,
  policy: "keep" | "cancel",
): Promise<void> {
  await tx.project.update({
    where: { id: project.id },
    data: { status: ProjectStatus.CANCELLED },
  });

  if (policy === "keep") return;

  const affected = await tx.financialRecord.updateMany({
    where: {
      projectId: project.id,
      status: { in: ["PENDING", "PARTIAL"] },
    },
    data: { status: "CANCELLED" },
  });

  await logActivity(
    {
      userId: project.userId,
      projectId: project.id,
      action: "FINANCIAL_CANCELLED",
      description: `Lançamentos financeiros do projeto "${project.title}" cancelados`,
      metadata: { affected: affected.count },
    },
    tx,
  );
}

export function isDeliveredStatus(status: ProjectStatus): boolean {
  return DELIVERED_STATUSES.includes(status);
}
