import { Prisma, type PrismaClient } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { financialRepo } from "@/repositories/financial.repository";
import { financialDefaultInclude } from "@/repositories/selects";
import { serializeFinancial } from "@/lib/serialize";
import { paginate, toSkipTake } from "@/lib/pagination";
import { NotFoundError } from "@/lib/errors";
import { logActivity } from "@/services/activity.service";
import { clientService } from "@/services/client.service";
import { projectService } from "@/services/project.service";
import {
  deriveFinancialStatus,
  financialToPaymentStatus,
} from "@/services/financial.rules";
import { nowRef, startOfMonth, startOfNextMonth } from "@/utils/date";
import type {
  CreateFinancialInput,
  ListFinancialQuery,
  UpdateFinancialInput,
} from "@/schemas/financial.schema";

type Tx = Prisma.TransactionClient | PrismaClient;

/**
 * Recompute `paidAmount`, `status` and `paidAt` for a record from its payments,
 * then keep the linked project's coarse paymentStatus in sync. Idempotent.
 */
export async function recomputeFinancialRecord(recordId: string, tx: Tx = prisma) {
  const record = await tx.financialRecord.findUnique({
    where: { id: recordId },
    include: { payments: true },
  });
  if (!record) throw new NotFoundError("Lançamento financeiro");

  const paid = record.payments.reduce<Prisma.Decimal>(
    (acc, p) => acc.plus(p.amount),
    new Prisma.Decimal(0),
  );
  const status = deriveFinancialStatus(record.amount, paid, record.status);
  const lastPayment = record.payments
    .slice()
    .sort((a, b) => b.paymentDate.getTime() - a.paymentDate.getTime())[0];

  const updated = await tx.financialRecord.update({
    where: { id: recordId },
    data: {
      paidAmount: paid,
      status,
      paidAt: status === "PAID" ? lastPayment?.paymentDate ?? record.paidAt ?? new Date() : null,
    },
  });

  if (updated.projectId) {
    await tx.project.update({
      where: { id: updated.projectId },
      data: { paymentStatus: financialToPaymentStatus(status) },
    });
  }

  return updated;
}

function resolveReference(input: {
  referenceMonth?: number;
  referenceYear?: number;
  dueDate?: Date;
  paidAt?: Date;
}) {
  if (input.referenceMonth && input.referenceYear) {
    return { month: input.referenceMonth, year: input.referenceYear };
  }
  const basis = input.paidAt ?? input.dueDate ?? new Date();
  return nowRef(basis);
}

function buildWhere(userId: string, q: ListFinancialQuery): Prisma.FinancialRecordWhereInput {
  const where: Prisma.FinancialRecordWhereInput = { userId };
  if (q.type) where.type = q.type;
  if (q.status) where.status = Array.isArray(q.status) ? { in: q.status } : q.status;
  if (q.category) where.category = { equals: q.category, mode: "insensitive" };
  if (q.clientId) where.clientId = q.clientId;
  if (q.projectId) where.projectId = q.projectId;
  if (q.autoGenerated !== undefined) where.autoGenerated = q.autoGenerated;

  if (q.from || q.to) {
    where.OR = [
      {
        dueDate: {
          ...(q.from ? { gte: q.from } : {}),
          ...(q.to ? { lte: q.to } : {}),
        },
      },
      {
        createdAt: {
          ...(q.from ? { gte: q.from } : {}),
          ...(q.to ? { lte: q.to } : {}),
        },
      },
    ];
  } else if (q.month && q.year) {
    where.referenceMonth = q.month;
    where.referenceYear = q.year;
  } else if (q.year) {
    where.referenceYear = q.year;
  }

  if (q.search) {
    where.AND = [
      {
        OR: [
          { description: { contains: q.search, mode: "insensitive" } },
          { category: { contains: q.search, mode: "insensitive" } },
          { notes: { contains: q.search, mode: "insensitive" } },
        ],
      },
    ];
  }

  return where;
}

export const financialService = {
  buildWhere,

  async list(userId: string, query: ListFinancialQuery) {
    const { page, pageSize, sortBy, sortDir } = query;
    const where = buildWhere(userId, query);
    const { skip, take } = toSkipTake({ page, pageSize });
    const [rows, total] = await financialRepo.list(where, { [sortBy]: sortDir }, skip, take);
    return paginate(rows.map(serializeFinancial), total, { page, pageSize });
  },

  async get(userId: string, id: string) {
    const row = await financialRepo.findForUser(userId, id);
    if (!row) throw new NotFoundError("Lançamento financeiro");
    return serializeFinancial(row);
  },

  async create(userId: string, input: CreateFinancialInput) {
    if (input.clientId) await clientService.assertOwned(userId, input.clientId);
    if (input.projectId) await projectService.assertOwned(userId, input.projectId);

    const ref = resolveReference(input);
    const amount = new Prisma.Decimal(input.amount);
    const initialPaid = input.initialPaidAmount
      ? new Prisma.Decimal(input.initialPaidAmount)
      : new Prisma.Decimal(0);
    const status =
      input.status ?? deriveFinancialStatus(amount, initialPaid, "PENDING");

    const record = await prisma.$transaction(async (tx) => {
      const created = await tx.financialRecord.create({
        data: {
          userId,
          type: input.type,
          category: input.category,
          description: input.description,
          amount,
          paidAmount: initialPaid,
          status,
          projectId: input.projectId ?? null,
          clientId: input.clientId ?? null,
          dueDate: input.dueDate ?? null,
          paidAt: input.paidAt ?? null,
          referenceMonth: ref.month,
          referenceYear: ref.year,
          paymentMethod: input.paymentMethod ?? null,
          notes: input.notes ?? null,
          autoGenerated: false,
        },
      });

      if (initialPaid.gt(0)) {
        await tx.payment.create({
          data: {
            financialRecordId: created.id,
            amount: initialPaid,
            paymentDate: input.paidAt ?? new Date(),
            paymentMethod: input.paymentMethod ?? null,
            notes: "Pagamento inicial",
          },
        });
        await recomputeFinancialRecord(created.id, tx);
      }

      await logActivity(
        {
          userId,
          projectId: created.projectId,
          action: "FINANCIAL_CREATED",
          description: `Lançamento "${created.description}" criado (${created.type})`,
          metadata: { financialRecordId: created.id, amount: amount.toString() },
        },
        tx,
      );

      return tx.financialRecord.findUniqueOrThrow({
        where: { id: created.id },
        include: financialDefaultInclude,
      });
    });

    return serializeFinancial(record);
  },

  async update(userId: string, id: string, input: UpdateFinancialInput) {
    const current = await financialRepo.findRaw(userId, id);
    if (!current) throw new NotFoundError("Lançamento financeiro");

    if (input.clientId) await clientService.assertOwned(userId, input.clientId);
    if (input.projectId) await projectService.assertOwned(userId, input.projectId);

    const data: Prisma.FinancialRecordUpdateInput = {};
    if (input.type !== undefined) data.type = input.type;
    if (input.category !== undefined) data.category = input.category;
    if (input.description !== undefined) data.description = input.description;
    if (input.amount !== undefined) data.amount = new Prisma.Decimal(input.amount);
    if (input.dueDate !== undefined) data.dueDate = input.dueDate ?? null;
    if (input.paidAt !== undefined) data.paidAt = input.paidAt ?? null;
    if (input.referenceMonth !== undefined) data.referenceMonth = input.referenceMonth;
    if (input.referenceYear !== undefined) data.referenceYear = input.referenceYear;
    if (input.paymentMethod !== undefined) data.paymentMethod = input.paymentMethod ?? null;
    if (input.notes !== undefined) data.notes = input.notes ?? null;
    if (input.projectId !== undefined)
      data.project = input.projectId ? { connect: { id: input.projectId } } : { disconnect: true };
    if (input.clientId !== undefined)
      data.client = input.clientId ? { connect: { id: input.clientId } } : { disconnect: true };
    if (input.status !== undefined) data.status = input.status;

    const updated = await prisma.$transaction(async (tx) => {
      await tx.financialRecord.update({ where: { id }, data });
      // Amount/status/payment set may have shifted the derived state.
      const recomputed = await recomputeFinancialRecord(id, tx);

      // Explicit status wins over the derived one (e.g. manual CANCELLED / PAID).
      if (input.status !== undefined && input.status !== recomputed.status) {
        await tx.financialRecord.update({ where: { id }, data: { status: input.status } });
      }

      await logActivity(
        {
          userId,
          projectId: current.projectId,
          action: "FINANCIAL_UPDATED",
          description: `Lançamento "${input.description ?? current.description}" atualizado`,
          metadata: { financialRecordId: id, changes: input },
        },
        tx,
      );

      return tx.financialRecord.findUniqueOrThrow({
        where: { id },
        include: financialDefaultInclude,
      });
    });

    return serializeFinancial(updated);
  },

  async remove(userId: string, id: string) {
    const current = await financialRepo.findRaw(userId, id);
    if (!current) throw new NotFoundError("Lançamento financeiro");

    await prisma.$transaction(async (tx) => {
      await tx.financialRecord.delete({ where: { id } });
      if (current.projectId) {
        await tx.project.update({
          where: { id: current.projectId },
          data: { paymentStatus: "PENDING" },
        });
      }
      await logActivity(
        {
          userId,
          projectId: current.projectId,
          action: "FINANCIAL_DELETED",
          description: `Lançamento "${current.description}" removido`,
          metadata: { financialRecordId: id },
        },
        tx,
      );
    });

    return { id };
  },

  /** Records tied to a reference month (used by dashboard & reports). */
  monthWhere(userId: string, month: number, year: number): Prisma.FinancialRecordWhereInput {
    return { userId, referenceMonth: month, referenceYear: year };
  },

  dateRangeForMonth(month: number, year: number) {
    return {
      gte: startOfMonth({ month, year }),
      lt: startOfNextMonth({ month, year }),
    };
  },
};
