import type {
  ActivityAction,
  FinancialStatus,
  FinancialType,
  PaymentStatus,
  Priority,
  ProjectStatus,
} from "@prisma/client";

export type {
  ActivityAction,
  FinancialStatus,
  FinancialType,
  PaymentStatus,
  Priority,
  ProjectStatus,
};

export interface Paginated<T> {
  items: T[];
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

export interface ClientDTO {
  id: string;
  name: string;
  companyName: string | null;
  email: string | null;
  phone: string | null;
  whatsapp: string | null;
  instagram: string | null;
  notes: string | null;
  projectsCount?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface KanbanColumnDTO {
  id: string;
  name: string;
  slug: string;
  position: number;
  color: string | null;
  isDeliveredColumn: boolean;
  isDefault: boolean;
  cardsCount?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProjectKanbanDTO {
  columnId: string;
  columnName: string;
  columnSlug: string;
  position: number;
}

export interface ProjectDTO {
  id: string;
  clientId: string;
  client?: { id: string; name: string; companyName: string | null };
  title: string;
  description: string | null;
  projectType: string | null;
  value: number;
  entryDate: Date;
  deadline: Date | null;
  deliveredAt: Date | null;
  completedAt: Date | null;
  status: ProjectStatus;
  priority: Priority;
  paymentStatus: PaymentStatus;
  paymentMethod: string | null;
  color: string | null;
  notes: string | null;
  kanban: ProjectKanbanDTO | null;
  financial?: FinancialRecordDTO[];
  createdAt: Date;
  updatedAt: Date;
}

export interface PaymentDTO {
  id: string;
  financialRecordId: string;
  amount: number;
  paymentDate: Date;
  paymentMethod: string | null;
  notes: string | null;
  createdAt: Date;
}

export interface FinancialRecordDTO {
  id: string;
  projectId: string | null;
  clientId: string | null;
  type: FinancialType;
  category: string;
  description: string;
  amount: number;
  paidAmount: number;
  remainingAmount: number;
  status: FinancialStatus;
  dueDate: Date | null;
  paidAt: Date | null;
  referenceMonth: number;
  referenceYear: number;
  paymentMethod: string | null;
  notes: string | null;
  autoGenerated: boolean;
  payments?: PaymentDTO[];
  project?: { id: string; title: string } | null;
  client?: { id: string; name: string } | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ActivityDTO {
  id: string;
  projectId: string | null;
  action: ActivityAction;
  description: string;
  metadata: unknown;
  createdAt: Date;
}

export interface DashboardSummary {
  period: { month: number; year: number };
  revenue: {
    forecast: number; // faturamento previsto (todos os INCOME do mês)
    received: number; // faturamento realizado / recebido
    pending: number; // a receber
  };
  expenses: {
    total: number;
    paid: number;
    pending: number;
  };
  netProfit: number; // recebido - despesas pagas
  projectedNetProfit: number; // previsto - despesas totais
  projects: {
    total: number;
    delivered: number;
    inProgress: number;
    cancelled: number;
  };
  averageTicket: number;
}
