import { z } from "zod";
import { FinancialType, FinancialStatus } from "@prisma/client";
import {
  dateSchema,
  idSchema,
  moneySchema,
  paginationSchema,
  positiveMoneySchema,
} from "@/schemas/common.schema";

export const financialTypeSchema = z.nativeEnum(FinancialType);
export const financialStatusSchema = z.nativeEnum(FinancialStatus);

/** Suggested categories (not enforced — free text is allowed for flexibility). */
export const INCOME_CATEGORIES = [
  "Edição de Vídeo",
  "Filmagem",
  "Fotografia",
  "Projeto Especial",
  "Outros",
] as const;

export const EXPENSE_CATEGORIES = [
  "Assinaturas",
  "Equipamentos",
  "Software",
  "Freelancer",
  "Transporte",
  "Marketing",
  "Outros",
] as const;

const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .optional()
    .or(z.literal("").transform(() => undefined));

export const createFinancialSchema = z
  .object({
    type: financialTypeSchema,
    category: z.string().trim().min(1, "categoria obrigatória").max(80),
    description: z.string().trim().min(1, "descrição obrigatória").max(240),
    amount: positiveMoneySchema,
    status: financialStatusSchema.optional(),
    projectId: idSchema.optional(),
    clientId: idSchema.optional(),
    dueDate: dateSchema.optional(),
    paidAt: dateSchema.optional(),
    referenceMonth: z.coerce.number().int().min(1).max(12).optional(),
    referenceYear: z.coerce.number().int().min(2000).max(2100).optional(),
    paymentMethod: optionalText(60),
    notes: optionalText(5000),
    /** Optional initial payment registered together with the record. */
    initialPaidAmount: moneySchema.optional(),
  })
  .refine(
    (v) => (v.referenceMonth == null) === (v.referenceYear == null),
    { message: "informe mês e ano de referência juntos", path: ["referenceMonth"] },
  );
export type CreateFinancialInput = z.infer<typeof createFinancialSchema>;

export const updateFinancialSchema = z
  .object({
    type: financialTypeSchema.optional(),
    category: z.string().trim().min(1).max(80).optional(),
    description: z.string().trim().min(1).max(240).optional(),
    amount: positiveMoneySchema.optional(),
    status: financialStatusSchema.optional(),
    projectId: idSchema.nullable().optional(),
    clientId: idSchema.nullable().optional(),
    dueDate: dateSchema.nullable().optional(),
    paidAt: dateSchema.nullable().optional(),
    referenceMonth: z.coerce.number().int().min(1).max(12).optional(),
    referenceYear: z.coerce.number().int().min(2000).max(2100).optional(),
    paymentMethod: optionalText(60),
    notes: optionalText(5000),
  })
  .refine((v) => Object.keys(v).length > 0, { message: "nenhum campo para atualizar" });
export type UpdateFinancialInput = z.infer<typeof updateFinancialSchema>;

export const listFinancialQuerySchema = paginationSchema.extend({
  sortBy: z
    .enum(["createdAt", "updatedAt", "dueDate", "paidAt", "amount", "referenceYear"])
    .default("createdAt"),
  type: financialTypeSchema.optional(),
  status: z.union([financialStatusSchema, z.array(financialStatusSchema)]).optional(),
  category: z.string().trim().max(80).optional(),
  clientId: idSchema.optional(),
  projectId: idSchema.optional(),
  month: z.coerce.number().int().min(1).max(12).optional(),
  year: z.coerce.number().int().min(2000).max(2100).optional(),
  from: dateSchema.optional(),
  to: dateSchema.optional(),
  autoGenerated: z
    .enum(["true", "false"])
    .transform((v) => v === "true")
    .optional(),
});
export type ListFinancialQuery = z.infer<typeof listFinancialQuerySchema>;
