/**
 * End-to-end verification of the Kanban → Financial automation, run directly
 * against the service layer (no HTTP). Requires a reachable DATABASE_URL.
 *
 *   npx tsx scripts/verify-flow.ts
 *
 * Creates an isolated throwaway user, exercises the full chain, asserts the
 * invariants, then deletes everything it created.
 */
import { prisma } from "../src/lib/prisma";
import { userService } from "../src/services/user.service";
import { clientService } from "../src/services/client.service";
import { projectService } from "../src/services/project.service";
import { financialService } from "../src/services/financial.service";
import { paymentService } from "../src/services/payment.service";
import { dashboardService } from "../src/services/dashboard.service";
import { kanbanService } from "../src/services/kanban.service";

let passed = 0;
function assert(cond: unknown, label: string) {
  if (!cond) throw new Error(`✗ ${label}`);
  passed++;
  console.log(`  ✓ ${label}`);
}

async function main() {
  const email = `verify+${Date.now()}@editflow.dev`;
  const user = await userService.register({ name: "Verify Bot", email, password: "verify12345" });
  console.log(`\nThrowaway user: ${email}\n`);

  try {
    // 1. Client + project
    const client = await clientService.create(user.id, { name: "Cliente Teste" });
    const project = await projectService.create(user.id, {
      clientId: client.id,
      title: "Vídeo Institucional Empresa X",
      projectType: "Edição de Vídeo",
      value: 2500,
      priority: "MEDIUM",
      paymentStatus: "PENDING",
    });
    assert(project.status === "NEW", "projeto criado com status NEW");
    assert(project.kanban?.columnSlug === "novos-projetos", "projeto entrou na 1ª coluna do Kanban");

    // 2. No financial record yet
    const before = await financialService.list(user.id, { page: 1, pageSize: 50, sortBy: "createdAt", sortDir: "desc" } as never);
    assert(before.total === 0, "nenhum lançamento financeiro antes da entrega");

    // 3. Move to the delivered column
    const columns = await kanbanService.listColumns(user.id);
    const delivered = columns.find((c) => c.isDeliveredColumn)!;
    const moved = await projectService.move(user.id, project.id, { columnId: delivered.id });
    assert(moved.status === "DELIVERED", "projeto marcado como DELIVERED ao mover");
    assert(moved.deliveredAt != null, "deliveredAt preenchido automaticamente");

    const afterMove = await financialService.list(user.id, { page: 1, pageSize: 50, sortBy: "createdAt", sortDir: "desc" } as never);
    assert(afterMove.total === 1, "1 lançamento financeiro criado automaticamente");
    const record = afterMove.items[0];
    assert(record.type === "INCOME" && record.amount === 2500, "lançamento INCOME de 2500");
    assert(record.autoGenerated, "lançamento marcado como autoGenerated");
    assert(record.status === "PENDING", "status financeiro PENDING (entregue ≠ pago)");

    // 4. Idempotency — move back and forth (reopen removes the premature
    //    record when nothing was paid; re-delivery recreates exactly one).
    const editing = columns.find((c) => c.slug === "em-edicao")!;
    await projectService.move(user.id, project.id, { columnId: editing.id });
    const reopened = await projectService.get(user.id, project.id);
    assert(reopened.status === "EDITING" && reopened.deliveredAt == null, "reabrir limpa o status de entrega");
    await projectService.move(user.id, project.id, { columnId: delivered.id });
    const afterBounce = await financialService.list(user.id, { page: 1, pageSize: 50, sortBy: "createdAt", sortDir: "desc" } as never);
    assert(afterBounce.total === 1, "sem duplicidade após mover várias vezes");
    const currentRecordId = afterBounce.items[0].id;

    // 5. Value change propagates
    await projectService.update(user.id, project.id, { value: 3000 });
    const recAfterValue = await financialService.get(user.id, currentRecordId);
    assert(recAfterValue.amount === 3000, "valor do lançamento atualizado junto com o projeto");

    // 6. Partial payment
    const partial = await paymentService.create(user.id, currentRecordId, { amount: 1000 });
    assert(partial.paidAmount === 1000 && partial.remainingAmount === 2000, "pagamento parcial: saldo 2000");
    assert(partial.status === "PARTIAL", "status → PARTIAL");
    const projPartial = await projectService.get(user.id, project.id);
    assert(projPartial.paymentStatus === "PARTIAL", "paymentStatus do projeto sincronizado → PARTIAL");

    // 7. Settle
    const settled = await paymentService.create(user.id, currentRecordId, { amount: 2000 });
    assert(settled.status === "PAID" && settled.remainingAmount === 0, "quitação → PAID, saldo 0");
    const projPaid = await projectService.get(user.id, project.id);
    assert(projPaid.paymentStatus === "PAID", "paymentStatus do projeto → PAID");

    // 8. Overpay guard
    let blocked = false;
    try {
      await paymentService.create(user.id, currentRecordId, { amount: 500 });
    } catch {
      blocked = true;
    }
    assert(blocked, "pagamento acima do saldo é bloqueado (sem allowOverpay)");

    // 9. Dashboard reflects it
    const summary = await dashboardService.summary(user.id);
    assert(summary.revenue.forecast >= 3000, "dashboard: faturamento previsto inclui o projeto");
    assert(summary.revenue.received >= 3000, "dashboard: faturamento recebido inclui o projeto");

    console.log(`\n✔ ${passed} verificações OK\n`);
  } finally {
    await prisma.user.delete({ where: { id: user.id } });
    await prisma.$disconnect();
    console.log("Throwaway user removido.");
  }
}

main().catch(async (e) => {
  console.error(`\n${e instanceof Error ? e.message : e}\n`);
  await prisma.$disconnect();
  process.exit(1);
});
